server:
    port: 5000
datasets:
    landsat-aws:
        type: Polygon
        title: my dataset
        abstract: my dataset
        keywords: kw1,kw2
        crs:
            - CRS84
        links:
            - type: information
              url: http://example.org/dataset/index.html
            - type: download
              url: http://example.org/dataset/data.tgz
        extents:
            spatial:
                bbox: [-180,-90,180,90]
            temporal:
                begin: 2011-11-11
                end: now  # or empty
        data:
            type: Elasticsearch
            url: http://localhost:9200/index/type
            id_field: id_
