FROM geopython/pygeoapi:latest

COPY ./sensorthings.pygeoapi.config.yml /pygeoapi/local.config.yml
COPY ./sensorthings.py /pygeoapi/pygeoapi/provider/sensorthings.py
COPY ./plugin.py /pygeoapi/pygeoapi/plugin.py