# =================================================================
#
# Authors: Benjamin Webb <benjamin.miller.webb@gmail.com>
#
# Copyright (c) 2021 Benjamin Webb
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

version: "3"

services:

  pygeoapi:
    image: geopython/pygeoapi:latest
    ports:
      - "5000:80"
    volumes:
      - ./brgm.sta.pygeoapi.config.yml:/pygeoapi/local.config.yml

#     depends_on:
#       - web
#     restart: always
#   web:
#     image: fraunhoferiosb/frost-server:latest
#     environment:
#       - serviceRootUrl=http://localhost:8080/FROST-Server
#       - http_cors_enable=true
#       - http_cors_allowed.origins=*
#       - persistence_db_driver=org.postgresql.Driver
#       - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
#       - persistence_db_username=sensorthings
#       - persistence_db_password=ChangeMe
#       - persistence_autoUpdateDatabase=true
#     ports:
#       - 8080:8080
#       - 1883:1883
#     depends_on:
#       - database

#   database:
#     image: postgis/postgis:11-2.5-alpine
#     environment:
#       - POSTGRES_DB=sensorthings
#       - POSTGRES_USER=sensorthings
#       - POSTGRES_PASSWORD=ChangeMe
#     volumes:
#       - postgis_volume:/var/lib/postgresql/data
# volumes:
#     postgis_volume:
