-- Enable PostGIS extension immediately
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgrouting;

CREATE TYPE "celltype" AS ENUM (
  'space',
  'boundary'
);

CREATE TYPE "node_edge_type" AS ENUM (
  'node',
  'edge'
);

CREATE TYPE "theme_type" AS ENUM (
  'physical',
  'virtual',
  'tags',
  'unknown'
);

CREATE TYPE "topo_type" AS ENUM (
  'contains',
  'overlaps',
  'equals',
  'within',
  'crosses',
  'others'
);

CREATE TABLE "collection" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_str" varchar UNIQUE,
  "collection_property" jsonb
);

CREATE TABLE "indoorfeature" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_str" varchar,
  "collection_id" bigint NOT NULL,
  "geojson_geometry" geometry,
  "geojson_properties" jsonb
);

CREATE TABLE "thematiclayer" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_str" varchar,
  "primalspace_id_str" varchar,
  "dualspace_id_str" varchar,
  "collection_id" bigint NOT NULL,
  "indoorfeature_id" bigint NOT NULL,
  "semantic_extension" bool NOT NULL,
  "p_creation_datetime" timestamp,
  "p_termination_datetime" timestamp,
  "d_creation_datetime" timestamp,
  "d_termination_datetime" timestamp,
  "is_logical" bool,
  "is_directed" bool,
  "theme" theme_type NOT NULL
);

CREATE TABLE "cell_space_n_boundary" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_str" varchar,
  "type" celltype NOT NULL,
  "collection_id" bigint NOT NULL,
  "indoorfeature_id" bigint NOT NULL,
  "thematiclayer_id" bigint NOT NULL,
  "2D_geometry" geometry,
  "3D_geometry" jsonb,
  "cell_name" varchar,
  "duality_id" bigint,
  "level" varchar,
  "poi" bool,
  "is_virtual" bool,
  "external_reference" jsonb,
  "bounded_by_cell_id" bigint
);

CREATE TABLE "node_n_edge" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_str" varchar,
  "type" node_edge_type NOT NULL,
  "collection_id" bigint NOT NULL,
  "indoorfeature_id" bigint NOT NULL,
  "thematiclayer_id" bigint NOT NULL,
  "geometry_val" geometry,
  "duality_id" bigint,
  "weight" float
);

CREATE TABLE "connects" (
  "node_source_id" bigint NOT NULL,
  "node_target_id" bigint NOT NULL,
  "edge_id" bigint NOT NULL
);

CREATE TABLE "interlayerconnection" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_str" varchar,
  "collection_id" bigint NOT NULL,
  "indoorfeature_id" bigint NOT NULL,
  "connected_layer_a" bigint NOT NULL,
  "connected_layer_b" bigint NOT NULL,
  "connected_cell_a" bigint,
  "connected_cell_b" bigint,
  "connected_node_a" bigint,
  "connected_node_b" bigint,
  "topo_type" topo_type NOT NULL,
  "comment" varchar
);

ALTER TABLE "indoorfeature" ADD FOREIGN KEY ("collection_id") REFERENCES "collection" ("id");

ALTER TABLE "thematiclayer" ADD FOREIGN KEY ("collection_id") REFERENCES "collection" ("id");

ALTER TABLE "thematiclayer" ADD FOREIGN KEY ("indoorfeature_id") REFERENCES "indoorfeature" ("id");

ALTER TABLE "cell_space_n_boundary" ADD FOREIGN KEY ("collection_id") REFERENCES "collection" ("id");

ALTER TABLE "cell_space_n_boundary" ADD FOREIGN KEY ("indoorfeature_id") REFERENCES "indoorfeature" ("id");

ALTER TABLE "cell_space_n_boundary" ADD FOREIGN KEY ("thematiclayer_id") REFERENCES "thematiclayer" ("id");

ALTER TABLE "node_n_edge" ADD FOREIGN KEY ("collection_id") REFERENCES "collection" ("id");

ALTER TABLE "node_n_edge" ADD FOREIGN KEY ("indoorfeature_id") REFERENCES "indoorfeature" ("id");

ALTER TABLE "node_n_edge" ADD FOREIGN KEY ("thematiclayer_id") REFERENCES "thematiclayer" ("id");

ALTER TABLE "connects" ADD FOREIGN KEY ("node_source_id") REFERENCES "node_n_edge" ("id");

ALTER TABLE "connects" ADD FOREIGN KEY ("node_target_id") REFERENCES "node_n_edge" ("id");

ALTER TABLE "connects" ADD FOREIGN KEY ("edge_id") REFERENCES "node_n_edge" ("id");

ALTER TABLE "interlayerconnection" ADD FOREIGN KEY ("collection_id") REFERENCES "collection" ("id");

ALTER TABLE "interlayerconnection" ADD FOREIGN KEY ("indoorfeature_id") REFERENCES "indoorfeature" ("id");

ALTER TABLE "interlayerconnection" ADD FOREIGN KEY ("connected_layer_a") REFERENCES "thematiclayer" ("id");

ALTER TABLE "interlayerconnection" ADD FOREIGN KEY ("connected_layer_b") REFERENCES "thematiclayer" ("id");

-- Ensure Feature ID is unique within a Collection
ALTER TABLE "indoorfeature" ADD CONSTRAINT "uk_feature_per_collection" UNIQUE ("collection_id", "id_str");
-- Ensure Layer ID is unique within a Feature
ALTER TABLE "thematiclayer" ADD CONSTRAINT "uk_layer_per_feature" UNIQUE ("indoorfeature_id", "id_str");
-- Ensure Cell/Node ID is unique within a Feature
ALTER TABLE "cell_space_n_boundary" ADD CONSTRAINT "uk_cell_per_feature" UNIQUE ("indoorfeature_id", "id_str");
ALTER TABLE "node_n_edge" ADD CONSTRAINT "uk_node_per_feature" UNIQUE ("indoorfeature_id", "id_str");
ALTER TABLE "interlayerconnection" ADD CONSTRAINT "uk_ilc_per_feature" UNIQUE ("indoorfeature_id", "id_str");

CREATE INDEX IF NOT EXISTS idx_cell_geom ON "cell_space_n_boundary" USING GIST ("2D_geometry");

CREATE INDEX IF NOT EXISTS idx_layer_feature ON "thematiclayer" ("indoorfeature_id");

CREATE INDEX IF NOT EXISTS idx_cell_duality ON "cell_space_n_boundary" ("duality_id");
CREATE INDEX IF NOT EXISTS idx_node_duality ON "node_n_edge" ("duality_id");

CREATE INDEX IF NOT EXISTS idx_conn_source ON "connects" ("node_source_id");
CREATE INDEX IF NOT EXISTS idx_conn_target ON "connects" ("node_target_id");
CREATE INDEX IF NOT EXISTS idx_conn_edge ON "connects" ("edge_id");

CREATE INDEX IF NOT EXISTS idx_ilc_layer_a ON "interlayerconnection" ("connected_layer_a");
CREATE INDEX IF NOT EXISTS idx_ilc_layer_b ON "interlayerconnection" ("connected_layer_b");
