name: 'Perform CITE tests against a local teamengine instance'

on:
  push:
  pull_request:


jobs:
  perform-cite-testing:
    runs-on: ubuntu-22.04
    steps:

      - name: grab code
        uses: actions/checkout@v4

      - name: start pygeoapi with suitable CITE data and config
        run: >
          docker compose -f tests/cite/compose.test-cite.yaml up --detach

      - name: wait for pygeoapi to be usable
        uses: raschmitt/wait-for-healthy-container@v1.0.1
        with:
          container-name: pygeoapi-cite-pygeoapi-1
          timeout: 480

      - name: test ogcapi-features compliancy
        uses: OSGEO/ogc-cite-action@main
        with:
          test-suite-identifier: ogcapi-features-1.0
          test-session-arguments: >
            --test-suite-input iut http://localhost:5001 
            --test-suite-input noofcollections -1